name: Push Docker Manifest
description: Create and push a Docker manifest for multi-architecture images
inputs:
  images:
    description: A comma-delimited list of images to create a manifest for
    type: string
    required: true
  registry:
    description: The registry to push the manifest to
    type: string
    required: true
  tag:
    description: Release tag to tag the manifest with (manifests are tagged with SHA by default)
    type: string
    required: true
  amd-only:
    description: A comma-delimited list of images that are AMD only architecture
    type: string
  arm-only:
    description: A comma-delimited list of images that are ARM only architecture
    type: string
  retries:
    description: The number of times to attempt the action
    type: number
    default: 3
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
      env:
        AMD_ONLY: ${{ inputs.amd-only }}
        ARM_ONLY: ${{ inputs.arm-only }}
        IMAGES: ${{ inputs.images }}
        REGISTRY: ${{ inputs.registry }}
        RETRIES: ${{ inputs.retries }}
        TAG: ${{ inputs.tag }}
